FROM node:alpine

EXPOSE 5000

WORKDIR /app
COPY . /app

RUN apk add --no-cache bash && \ 
    npm install && \ 
    chown -R node /app

USER node

ENV API_URL="http://localhost:8000"

CMD ["npm", "start"]