FROM node:alpine

EXPOSE 8000

WORKDIR /app
COPY . /app

RUN apk add --no-cache bash && \ 
    npm install && \ 
    chown -R node /app

USER node

ENV FRONT_URL="http://localhost:5000"

CMD ["npm", "start"]
