version: '3.5'
services:
  frontend-app:
    image: frontend
    build: .
    container_name: frontend-app
    ports:
      - 5000:5000
  backend-app:
    image: backend
    build: .
    container_name: backend-app
    ports:
      - 8000:8000
    volumes:
      - ./backend-example-docker/logs.txt:/mydir/logs.txt
