version: '3.5'
services:
  frontend:
    image: ml-kurkkumopo-frontend
    build: .
    container_name: ml-kurkkumopo-frontend
    ports:
      - 3000:3000

  backend:
    image: ml-kurkkumopo-backend
    build: .
    container_name: ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model-dir:/src/model

  training:
    image: ml-kurkkumopo-training
    build: .
    container_name: ml-kurkkumopo-training
    volumes:
      - training-images:/src/imgs
      - training-csvs:/data
      - model-dir:/src/model

volumes:
  training-images:
  training-csvs:
  model-dir: