version: '3.5'
services:

  frontend-app:
    image: frontend
    build: .
    container_name: frontend-app

  backend-app:
    image: backend
    build: .
    container_name: backend-app
    restart: unless-stopped
    volumes:
      - ./backend-example-docker/logs.txt:/mydir/logs.txt
    environment:
      - REDIS=redis
      - DB_USERNAME=someuser
      - DB_PASSWORD=somepassword
      - DB_NAME=somedatabase
      - DB_HOST=db

  redis:
    image: redis
    container_name: redis-cont
    volumes:
      - ./data:/data
  
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_DB=somedatabase

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80


